[2024-04-05 19:32:26,386] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-10-31T00:00:00+00:00 [queued]>
[2024-04-05 19:32:26,390] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-10-31T00:00:00+00:00 [queued]>
[2024-04-05 19:32:26,390] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-04-05 19:32:26,390] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-04-05 19:32:26,390] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-04-05 19:32:26,408] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2022-10-31 00:00:00+00:00
[2024-04-05 19:32:26,410] {standard_task_runner.py:52} INFO - Started process 723902 to run task
[2024-04-05 19:32:26,412] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2022-10-31T00:00:00+00:00', '--job-id', '25', '--raw', '--subdir', 'DAGS_FOLDER/extrai_dados_climaticos.py', '--cfg-path', '/tmp/tmp5y9v2sdm', '--error-file', '/tmp/tmppk7os2fe']
[2024-04-05 19:32:26,412] {standard_task_runner.py:80} INFO - Job 25: Subtask cria_pasta
[2024-04-05 19:32:26,445] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-10-31T00:00:00+00:00 [running]> on host TEC017860.
[2024-04-05 19:32:26,488] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=cria_pasta
AIRFLOW_CTX_EXECUTION_DATE=2022-10-31T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-10-31T00:00:00+00:00
[2024-04-05 19:32:26,489] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2024-04-05 19:32:26,489] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'mkdir -p "/home/millenagena/Documents/airflowalura/semana=2022-11-07"']
[2024-04-05 19:32:26,493] {subprocess.py:85} INFO - Output:
[2024-04-05 19:32:26,495] {subprocess.py:92} INFO - mkdir: cannot create directory ‘/home/millenagena’: Permission denied
[2024-04-05 19:32:26,495] {subprocess.py:96} INFO - Command exited with return code 1
[2024-04-05 19:32:26,501] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/dimitri/dimitri/airflowalura/venv/lib/python3.10/site-packages/airflow/operators/bash.py", line 194, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-04-05 19:32:26,503] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20221031T000000, start_date=20240405T223226, end_date=20240405T223226
[2024-04-05 19:32:26,515] {standard_task_runner.py:92} ERROR - Failed to execute job 25 for task cria_pasta (Bash command failed. The command returned a non-zero exit code 1.; 723902)
[2024-04-05 19:32:26,554] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-04-05 19:32:26,577] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
