[2024-04-05 19:33:57,851] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta manual__2024-04-05T22:33:52.608349+00:00 [queued]>
[2024-04-05 19:33:57,859] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta manual__2024-04-05T22:33:52.608349+00:00 [queued]>
[2024-04-05 19:33:57,859] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-04-05 19:33:57,859] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-04-05 19:33:57,859] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-04-05 19:33:57,878] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2024-04-05 22:33:52.608349+00:00
[2024-04-05 19:33:57,881] {standard_task_runner.py:52} INFO - Started process 724771 to run task
[2024-04-05 19:33:57,884] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'manual__2024-04-05T22:33:52.608349+00:00', '--job-id', '64', '--raw', '--subdir', 'DAGS_FOLDER/extrai_dados_climaticos.py', '--cfg-path', '/tmp/tmp0wint3e5', '--error-file', '/tmp/tmps3jc08fc']
[2024-04-05 19:33:57,884] {standard_task_runner.py:80} INFO - Job 64: Subtask cria_pasta
[2024-04-05 19:33:57,920] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta manual__2024-04-05T22:33:52.608349+00:00 [running]> on host TEC017860.
[2024-04-05 19:33:57,978] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=cria_pasta
AIRFLOW_CTX_EXECUTION_DATE=2024-04-05T22:33:52.608349+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-04-05T22:33:52.608349+00:00
[2024-04-05 19:33:57,978] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2024-04-05 19:33:57,979] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'mkdir -p "/home/millenagena/Documents/airflowalura/semana=2024-04-01"']
[2024-04-05 19:33:57,984] {subprocess.py:85} INFO - Output:
[2024-04-05 19:33:57,985] {subprocess.py:92} INFO - mkdir: cannot create directory ‘/home/millenagena’: Permission denied
[2024-04-05 19:33:57,986] {subprocess.py:96} INFO - Command exited with return code 1
[2024-04-05 19:33:57,993] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/dimitri/dimitri/airflowalura/venv/lib/python3.10/site-packages/airflow/operators/bash.py", line 194, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-04-05 19:33:57,995] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20240405T223352, start_date=20240405T223357, end_date=20240405T223357
[2024-04-05 19:33:58,011] {standard_task_runner.py:92} ERROR - Failed to execute job 64 for task cria_pasta (Bash command failed. The command returned a non-zero exit code 1.; 724771)
[2024-04-05 19:33:58,020] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-04-05 19:33:58,047] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
