[2024-04-05 19:33:56,145] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2023-07-24T00:00:00+00:00 [queued]>
[2024-04-05 19:33:56,150] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2023-07-24T00:00:00+00:00 [queued]>
[2024-04-05 19:33:56,150] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-04-05 19:33:56,150] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-04-05 19:33:56,150] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-04-05 19:33:56,168] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2023-07-24 00:00:00+00:00
[2024-04-05 19:33:56,171] {standard_task_runner.py:52} INFO - Started process 724751 to run task
[2024-04-05 19:33:56,174] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2023-07-24T00:00:00+00:00', '--job-id', '63', '--raw', '--subdir', 'DAGS_FOLDER/extrai_dados_climaticos.py', '--cfg-path', '/tmp/tmpz859tsl9', '--error-file', '/tmp/tmpwi0w85ll']
[2024-04-05 19:33:56,174] {standard_task_runner.py:80} INFO - Job 63: Subtask cria_pasta
[2024-04-05 19:33:56,213] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2023-07-24T00:00:00+00:00 [running]> on host TEC017860.
[2024-04-05 19:33:56,279] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=cria_pasta
AIRFLOW_CTX_EXECUTION_DATE=2023-07-24T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-07-24T00:00:00+00:00
[2024-04-05 19:33:56,280] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2024-04-05 19:33:56,281] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'mkdir -p "/home/millenagena/Documents/airflowalura/semana=2023-07-31"']
[2024-04-05 19:33:56,289] {subprocess.py:85} INFO - Output:
[2024-04-05 19:33:56,290] {subprocess.py:92} INFO - mkdir: cannot create directory ‘/home/millenagena’: Permission denied
[2024-04-05 19:33:56,290] {subprocess.py:96} INFO - Command exited with return code 1
[2024-04-05 19:33:56,298] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/dimitri/dimitri/airflowalura/venv/lib/python3.10/site-packages/airflow/operators/bash.py", line 194, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-04-05 19:33:56,300] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20230724T000000, start_date=20240405T223356, end_date=20240405T223356
[2024-04-05 19:33:56,315] {standard_task_runner.py:92} ERROR - Failed to execute job 63 for task cria_pasta (Bash command failed. The command returned a non-zero exit code 1.; 724751)
[2024-04-05 19:33:56,357] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-04-05 19:33:56,386] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
